@startuml
/'2. ПРОЦЕДУРЫ ВЗАИМОДЕЙСТИЯ
   =========================================================================================================================
   Процедуры req и res необходимы для замены стандартного описания взаимодействия между участниками,
   Вам необходимо вызвать процедуру в редакторе, передать ей параметры:
   $initiator - участник-инициатор взаимодействия,
   $executor - участник-исполнитель взаимодействия,
   $liveLine - параметр управления линией жизни взаимодействия, подразумевается ++, --, --++, ++--
   $action - описание взаимодействия
   $comment - комментарий для данной операции
   Процедура во время исполнения автоматически вызывает другую вспомогательную процедуру - $processDescriptionBuilder,
   для построения карты процесса в виде текста с разделителями.
   Пример: req(Alice,Bob,++,Поздороваться,Alice всегда здоровается с Bob при встрече) заменяет строку вида Alice -> Bob ++: Поздороваться.
   Для удобства использования необходимо создать шаблон автоподстановки в используемой вами среде разработке. В IDEA это находится в меню
   settings -> editor -> LiveTemplates'/

!unquoted procedure req($initiator, $executor, $liveLine="",$action, $comment="")
    $initiator -> $executor $liveLine: $action
    !$id = $id + 1
    %invoke_procedure("$processDescriptionBuilder", $id, $initiator, $executor, $action, $comment)
!endprocedure

!unquoted procedure res($executor, $initiator, $liveLine="",$action, $comment="")
    $executor --> $initiator $liveLine: $action
    !$id = $id + 1
    %invoke_procedure("$processDescriptionBuilder", $id, $initiator, $executor, $action, $comment)
!endprocedure