@startuml
/'
Варианты альтов
1. самое начало, счетчик стрелок = 0, сценарий может начаться n разными способами
2. есть донорская стрелка, счетчик = i, у нее есть n альтернатив
3. середина диаграммы, счетчик равен i, сценарий может продолжиться n разными способами
4.
'/
@enduml