@startuml
/'1. ПАРАМЕТРЫ И РУБИЛЬНИКИ
=========================================================================================================================
Идентификатор взаимодействия, повторяет значение autonumber'/
!$id = 0

/'Параметр для формирования построчного отображения текста в ячейках таблицы'/
!$textResult = ""

/'Параметры, ограничивающие длину строк в ячейках в таблице'/
!$actionLength = 40
!$commentLength = 65

/'Счетчики для построения карты процессов'/
!$legendId = 0

/'Переменная с легендой диаграммы'/
!$diagramLegend = ""

/'Выявленные в процессе моделирования доработки'/
!$todoList = "| № | id обнаружения | Суть доработки|"
!$todoId = 0

/'Параметры, отвечающие за обработку имен и алиасов участников диаграммы'/
!$partiesMapper = ""
!$resultName = ""

/'Переменные, необходимые для функционирования автоответов'/
!$requestHistory = ""
!$ainitiator = ""
!$aexecutor = ""

/'Переменная для событий аудита'/
!$auditEventList = "| № | Код события | start event | end event | Статус | Описание |"
!$auditId = 0