@startuml
/'1. ПАРАМЕТРЫ И РУБИЛЬНИКИ
=========================================================================================================================
Идентификатор взаимодействия, повторяет значение autonumber'/
!$id = 0

/'Вспомогательные буфферные параметры'/
!$textResult = ""
!$actionResult = ""
!$commentResult = ""
!$initiatorName = ""
!$executorName = ""
!$getInitiator = ""
!$getExecutor = ""
!$getEvent = ""
!$getStatusEvent = ""
!$getStartEvent = ""
!$getFinishEvent = ""
!$getDescriptionEvent = ""
!$getType = ""

/'Параметры, ограничивающие длину строк в ячейках в таблице'/
!$actionLength = 20
!$commentLength = 35

/'Переменные с заголовками для легенды диаграммы'/
!$processMap = "| # | Инициатор | Исполнитель | Действие | Комментарий |"
!$auditTable = "| # | name | start | finish | status | description |"

/'Выявленные в процессе моделирования доработки'/
!$todoList = "| № | id обнаружения | Суть доработки|"
!$todoId = 0

/'Переменная для событий аудита'/
!$auditId = 0

