@startuml
/'1. ПАРАМЕТРЫ И РУБИЛЬНИКИ
=========================================================================================================================
Идентификатор взаимодействия, повторяет значение autonumber'/

!$id = 0

/'Параметр, содержащий символ переноса строки \n в описании взаимодействия и комментария к нему,
необходим для формирования построчного отображения текста в ячейках таблицы'/
!$textResult = ""

/'Параметры, ограничивающие длину строк с описанием взаимодействия и комментария к нему в таблице'/
!$actionLength = 20
!$commentLength = 30

/'Параметры, задающие шаблон табличного описания процессов'/
!$csvProcessDescription = "id;Инициатор;Получатель;Действие;Комментарий"
!$tableProcessDescription = "| id | Инициатор | Получатель | Действие | Комментарий |"

/'Параметры, отвечающие за обработку имен и алиасов участников диаграммы'/
!$partiesMapper = ""
!$resultName = ""

/'Переменные, необходимые для функционирования автоответов'/
!$requestHistory = ""
!$ainitiator = ""
!$aexecutor = ""

/'Переменные, используемые для создания списка дел'/
!$todoList = "| id | Где нашел | Суть/что надо сделать |"
!$todoId = 0
@enduml