@startuml
/'3. СЛУЖЕБНЫЕ ПРОЦЕДУРЫ
=========================================================================================================================
Вспомогательная процедура отрисовки участников: нужна только для формирования переменной с мапой имя-алиас
она нужна для формирования карты процесса'/
!unquoted procedure parties($partyType="participant", $name, $alias, $order="")
    !if $order != ""
        $partyType "$name" as $alias order $order
    !else
        $partyType "$name" as $alias
    !endif
    !$partiesMapper = $partiesMapper + $alias + ":" + $name + ";"
!endprocedure

/'Вспомогательная процедура получения имения участника по алиасу из маппера участников'/
!unquoted procedure $aliasToName($alias)
    !$resultName = %substr($partiesMapper, %strpos($partiesMapper, $alias))
    !$resultName = %substr($resultName, %strpos($resultName, ":"))
    !$resultName = %substr($resultName,1,%strpos($resultName,";")-1)
!endprocedure

/'Вспомогательная процедура, отвечает за построчное отображение текста в таблице'/
!unquoted procedure $textNewLineCutter($text, $length)
    !while %strpos(%substr($text,%intval($length)), " ") > 0 /'Пока в строке есть пробелы после ограничителя длины $length - делать перенос'/
        !$cutPosition = $length + %strpos(%substr($text,%intval($length)), " ") /'Поиск пробела'/
        !$textResult = $textResult + %substr($text, 0, $cutPosition) + " " + "\n"
        !$text = %substr($text,%intval($cutPosition))
    !endwhile
    !$textResult = $textResult + $text
!endprocedure

/'Процедура, отвечающая за формирование таблицы с описанием процесса
Процедура вызывается каждый раз с вызовом процедур взаимодействия.
Стоит обратить внимание на значение параметров $actionLength и $commentLength, - они
управляют длинной строки, отображаемой в ячейке таблицы. Это работает только для таблицы с
разделителем |, для ";" перенос строк не работает'/
!unquoted procedure $processDescriptionBuilder($int, $initiator, $executor, $action, $comment="")
    /'Форматируем текст действия в многострочный вид'/
    %invoke_procedure("$textNewLineCutter", $action,$actionLength) /'Форматирование текста построчно'/
    !$actionResult = $textResult
    !$textResult = ""
    /'Форматируем текст комментария в многострочный вид'/
    %invoke_procedure("$textNewLineCutter", $comment, $commentLength) /'Форматирование текста построчно'/
    !$commentResult = $textResult
    !$textResult = ""
    /'Получаем имя инициатора по его алиасу'/
    %invoke_procedure("$aliasToName", $initiator)
    !$initiatorName = $resultName
    !$resultName = ""
    /'Получаем имя исполнителя по его алиасу'/
    %invoke_procedure("$aliasToName", $executor)
    !$executorName = $resultName
    !$resultName = ""
    'Наполнение таблиц с разными разделителями: | - для него нужно построчное форматирование текста, и ; - для него не нужно построчное форматирование текста
    !$csvProcessDescription = $csvProcessDescription + %newline() + $int + ";" + $initiator + ";"+ $executor + ";" + $action + ";" + $comment
    !$tableProcessDescription = $tableProcessDescription + %newline() + "| " +  $int + " | " + $initiatorName + " | "+ $executorName + " | " + $actionResult + " | " + $commentResult + " |"
!end procedure

/'Процедура, отвечающая за отображение таблицы с описанием процесса.
Процедура принимает на вход значения 0 или 1, где 0 - табличное отображение карты процесса с переносом строк в ячейках,
а 1 - это отображение карты процесса в виде текста с разделителем ;
По умолчанию вызывается с 0.
Как использовать? Описание для IntelliJ IDEA - описываете свой процесс. Вызываете процедуру NOTE()
с любым параметром, далее кликаете правой кнопкой мыши по изображению и выбираете "Copy diagramm to clipbord as unicode ASCII",
в буфер скопируется изображение в формате markdown, вставляйте в любой текстовый редактор. Копируйте таблицы с разделителем, и т.д. на свое
усмотрение. Смотри отображение тестового примера в файле read.me'/
!unquoted procedure NOTE($mode=0)
!if $mode == 0
note across
=Таблица: карта процесса
====
$tableProcessDescription
end note

!elseif $mode == 1
note across
=Текстовое описание процесса (текст с разделителем)
====
$csvProcessDescription
end note
!endif
!end procedure
@enduml