@startuml
autonumber
Alice -> Bob: Authentication rquest
Bob --> Alice: Authentication rsponse
Alice -> Bob: Another authentication rquest
Alice <-- Bob: another authentication rsponse
note across
| columnName | columnName1 | columnName2 |
| value | value | value |
end note
@enduml