@startuml
autonumber
Alice -> Bob: Authentication request
Bob --> Alice: Authentication response
Alice -> Bob: Another authentication request
Alice <-- Bob: another authentication response
note across
| columnName | columnName1 | columnName2 |
| value | value | value |
end note
@enduml