@startuml
!include SequenseLib.puml

parties(actor,Alice,a)
parties(actor,Bob,b)
req("a","b","","AuthenticationRequest","Запрос аутентификации")
res("b","a","","AuthenticationRessponnse","Ответ аутентификации")
req("a","b","","AnotherAuthenticationRequest","Еще один запрос аутентификации")
res("b","a","","AnotherAuthenticationRessponnse","Еще один ответ аутентификации")

NOTE()
@enduml