@startuml
!include Functions/SequenceLib.v3

parties(actor, Валера ,valera)
parties(participant,InelliJ IDEA,idea)
box "Телеграмм" #dodgerblue
parties(queue,Чат с коллегами,chat)
end box
parties(actor,Коллега,colleague)
parties(participant,GiitHub,git)

req(valera,idea,++,Написание библиотеки, "Библиотека изначально пишется под себя, после отладки и переиспользования в работе возникает решение поделиться с коллегами.")
res(idea,valera,,Результат, "Отображение библиотеки, способов ее применения")
note across: Нижу в качестве примера вызываю функцию NOTE с парметром 1. \nОна накопительная, т.е. наполнение данными зависит от места выззова.
NOTE(1)

req("valera","idea","","Отправить в удаленный репозиторий", "Удаленный репозиторий лежит по адресу [[https://github.com/leraRadicovich/plantUML_Lib.git Репозиторий Валеры]]")
req(idea,git,++,PUSH Changes, Отправка изменений в удаленный репозиторий)
res(git,idea,--,HTTPS адрес репозитория)
res(idea,valera,--,Адррес файлов с примером и библиотекой на локальной машине, Для отправки в чат)
req(valera,chat,++, "Коллеги, поглядите, вот библиотека для рисования сиквенсов с автоматическим построением табличной карты процесса", Прикладываю файл библиотеки и ссылку на репозиторий)
req(valera,chat,,Буду рад обратной связи и предложениям, "Пока все работает на безвозмездной основе, после коммерческого релиза стандартный ценник - 5$")
req(chat,colleague,--++,Новое сообщение в чате)
req(colleague,chat,++,Прочитать сообщение, "Скачать файлы библиотеки и примера либо посмотреть репозиторий, открыть их в используемой среде разработки, возможно использовать в своей работе, возможно предложить идеит по улучшению или исправлению багов")
NOTE()

@enduml