@startuml
!include Functions/SequenceLib.v3.puml

parties(actor, Валера ,valera)
parties(participant,InelliJ IDEA,idea)
box "Телеграмм" #dodgerblue
parties(queue,Чат с коллегами,chat)
end box
parties(actor,Коллега,colleague)
parties(participant,GitHub,git)

rq(valera,idea,++,Написание библиотеки, "Библиотека изначально пишется под себя, после отладки и переиспользования в работе возникает решение поделиться с коллегами.")
rs(,,,Результат, "Отображение библиотеки, способов ее применения")
note across: Нижу в качестве примера вызываю функцию NOTE с параметром 1. \nОна накопительная, т.е. наполнение данными зависит от места выззова.
NOTE(1)

rq("valera","idea","","Отправить в удаленный репозиторий", "Удаленный репозиторий лежит по адресу [[https://github.com/leraRadicovich/plantUML_Lib.git Репозиторий Валеры]]")
rq(idea,git,++,PUSH Changes, Отправка изменений в удаленный репозиторий)
note across: Ниже в качестве примера вызываю функцию partnote - отображает часть карты процесса - последнюю нарисованную стрелку.
partnote()
alt dfsa
altrs(...,HTTPS адрес репозитория)
end
rs(,,--,HTTPS адрес репозитория)

'autors(--,Адррес файлов с примером и библиотекой на локальной машине, Для отправки в чат)
rq(valera,chat,++, "Коллеги, поглядите, вот библиотека для рисования сиквенсов с автоматическим построением табличной карты процесса", Прикладываю файл библиотеки и ссылку на репозиторий)
rq(valera,chat,,Буду рад обратной связи и предложениям, "Пока все работает на безвозмездной основе, после коммерческого релиза стандартный ценник - 5$")
rq(chat,colleague,--++,Новое сообщение в чате)
rq(colleague,chat,++,Прочитать сообщение, "Скачать файлы библиотеки и примера либо посмотреть репозиторий, открыть их в используемой среде разработки, возможно использовать в своей работе, возможно предложить идеит по улучшению или исправлению багов")
NOTE()

@enduml