'/ПАРАМЕТРЫ СТИЛЯ
hide unlinked
skinparam maxMessageSize 150
skinparam backgroundColor LightGray
skinparam sequence {
ArrowColor blue
LifeLineBorderColor blue
LifeLineBackgroundColor White
ParticipantBorderColor blue
ParticipantBackgroundColor lightBlue-DodgerBlue
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor darkblue
ActorBorderColor darkblue
ActorBackgroundColor DodgerBlue
ActorFontName Impact
ActorFontColor DarkBlue
ActorFontSize 17
}

<style>
legend {
FontSize 16
FontColor white
BackGroundColor black
}
</style>