'СЛУЖЕБНЫЕ ПРОЦЕДУРЫ'
'Процедура LEGEND() инициирует отображение на диаграмме легенды с картой процесса, представленном на диаграмме, в табличном виде'
!unquoted procedure LEGEND()
    legend left
    Карта процесса
    ====
    $tableProcessDescription
    end legend
!endprocedure

/'Процедура NOTE($mode=0)  инициирует отображение на диаграмме заметки с картой процесса, представленном на диаграмме, в табличном виде (mode=0, дефолтное значение)
и в виде текста с разделителем (mode=1)'/
!unquoted procedure NOTE($mode=0)

!if $mode == 0
note across
Таблица: карта процесса
====
$tableProcessDescription
end note

!elseif $mode == 1
note across
=Текстовое описание процесса (текст с разделителем)
====
$csvProcessDescription
end note
!endif
!endprocedure