'/ 4. ПЕРЕМЕННЫЕ, ИСПОЛЬЗУЕМЫЕ ВО ВСЕХ ФУНКЦИЯХ И ПРОЦЕДУРАХ - ГЛБАЛЬНЫЕ ПЕРЕМЕННЫЕ

    '/Счетчик отображаемой (программной) автонумерации стрелок
    !global $counter = 0

    '/Счетчик сквозной автонумерации всех вызовов, технический
    !global $techCounter = 0

    '/Счетчик донорских стрелок в КЭШе
    !global $donor = 0

    /'Дефолтны цвет для альта
    '/
    !global $altColor = "#chocolate"
    !global $altColorStep = 15

    '/Счетчик вложенности альтов
    !global $altLevel = 0

    '/Программный КЭШ донорских стрелок
    !global $cash = ""

    '/Буферная переменная для построения карты процесса в табличном виде и в виде текста с разделителем.
    '/См. процедуры LEGEND, NOTE
    !global $tableProcessDescription="| №\n | id | Инициатор\n | Исполнитель\n | Вызов/Метод\n | Комментарий\n |"
    !global $csvProcessDescription="№;id;Инициатор;Исполнитель;Вызов/метод;Комментарий"