@startuml

!include SequenseLib.puml

addBox("queue","test box", "pink", "",test component, test, 5)
DIAGRAMM_INIT(Отладка конфига для сиквенс-диаграммы)
note across
    %filename()
    27.02.2024
    by Patrushev Valery
end note

ALT(Первый вызов)
    ACTION(site,front,++,первый вызов,комментарий)
    ALT(Тест вложенного альта,,)
        ACTION(site,front,,первый вызов вложенного нулевого альта,комментарий)
    END_ALT()
ELSE_ALT(первый альт вызов)
    ACTION(site,front,,первый альт вызов,комментарий)
    ACTION(front,site,--++,первый ответ,Комментарий к вызову)
END_ALT()
    ACTION(front,site,,первый alt ответ\n рецепиент,еще какой-токомментарий)
ALT(Альтернатива один)
    ACTION(front,site,,первый alt ответ\n рецепиент,еще какой-токомментарий)
    ALT(проверка вложенного альта, 3)
        ACTION(site,user,,действие)
    ELSE_ALT(проверка еще одного условия во вложенности)
        ACTION(site,user,,действие)
        ALT(проверка вложенного альта 3 уровня, 4)
            ACTION(site,user,,действие)
        ALT(проверка вложенного альта 3 уровня, 4)
            ACTION(site,user,,действие)
        END_ALT()
        END_ALT()
        ACTION(site,user,,действие)
        ACTION(site,user,,действие)
    END_ALT()
    ACTION(front,site,,первый alt ответ,пояснение)
ELSE_ALT(Альтернатива один)
    ACTION(front,site,,второй alt ответ,другое пояснение)
END_ALT()
ACTION(front,site,,следующий шаг сценария,комментарий)
LEGEND()
NOTE(0)
@enduml