@startuml
!include SequenseLib.v.1.6.puml

addBox("queue","test box", "pink", "",test component, test, 5)
DIAGRAMM_INIT(Отладка конфига для сиквенс-диаграммы)
note across
    %filename()
    27.02.2024
    by Patrushev Valery
end note
user -> site++:траляля
site ->user--:траляля
==Макеты для понимания==
autonumber 1

group#moccasin %lighten(lightgreen,-10) <size:15> положение альта (1 кейс): альт после донорской стрелки
    user->site: донорская стрелка
    alt#yellow #orange 1 Условие (1 уровень)
        user->site: альтернативная стрелка
    else #orange 2 Условие (1 уровень)
        autonumber 2
        user->site: альтернативная стрелка
    end
else %lighten(lightgreen, -25) <size:15> положение альта (2 кейс): альт до донорской стрелки**
    alt#yellow #orange 1 Условие (1 уровень)
        site->user: альтернативная стрелка
    else #orange 2 Условие (1 уровень)
        autonumber 3
        site->user: альтернативная стрелка
    end
    autonumber 3
    site->user: донорская стрелка
else %lighten(lightgreen, -40) <size:15> положение альта (3 кейс): альт является донором для самого себя
    alt#yellow #orange 1 Условие (1 уровень)
        site->user: альтернативная стрелка
    else #orange 2 Условие (1 уровень)
        autonumber 4
        site->user: альтернативная стрелка
    end
end

group#moccasin %lighten(lightgreen,-10) <size:15> вложенность альта (1 кейс) + 3 кейса на положение
    user->site: донорская стрелка
    alt#yellow #orange 1 Условие (1 уровень)
        user->site: альтернативная стрелка
        alt#yellow %lighten(orange, -30) 1 Условие (2 уровень)
            user->site: альтернативная стрелка
        else %lighten(orange, -30) 2 Условие (2 уровень)
            autonumber 7
            user->site: альтернативная стрелка
        end
    else #orange 2 Условие (1 уровень)
        autonumber 6
        user->site: альтернативная стрелка
    end
end

note across #yellow
1. par, opt, group - не поднимают уровень, работают на том уровне, в котором вызываются
2. Простаня нумерация или сложная - нужно понять.
3. есть четыер кейса: альт после донорской стрелки (донорская существует), альт до донорской стрелки (донорская существет),
   альт до донорской стрелки (донорская не существет), альт вместо донорскй стрелки
4. Альты должны работать без уровнязависимых счетчиков

endnote


== конец макетов ==
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, ++, rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, ++, rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)
$action(site, front, POST/oauth2/authorize\nparams:{\nasdf\nfa\nsdfg}, , rjvvtynfhbq)


$alt(alt,condition1 alt,site,front,Check alt,,comment froCheck Alt 1 level)
    $alt(alt,condition1 alt,site,front,Check alt,,comment froCheck Alt 1 level)
    $alt(,,site,front,Check alt,,comment froCheck Alt 1 level)
    $alt(else,condition2 alt,site,front,Check alt,,comment froCheck Alt 1 level)
    $alt(else,condition3 alt,site,front,Check alt,,comment froCheck Alt 1 level)
    $alt(end)
$alt(,,site,front,Check alt,,comment froCheck Alt 1 level)
$alt(else,condition2 alt,site,front,Check alt,,comment froCheck Alt 1 level)
$alt(end)
$action(site,front, POST/check/actionAlt,,comment for check actionAlt)
$actionAlt(alt,condition1 actionAlt,site,front,altCheck,,comment froCheck actionAlt 1 level)
    $actionAlt(,condition1,site,front,altCheck,,comment froCheck actionAlt 1 level)
$actionAlt(end)

$cash(get)
note across
%chr(64) - %ord(%chr(64))
%chr(65) - %ord(%chr(65))
end note

NOTE(1)
LEGEND()

@enduml