@startuml

abstract SEQUENCE.Functions.SequenceLib_v3
class SEQUENCE.Functions.SequenceStyle
class SEQUENCE.Functions.ParametresAndSwitchers
class SEQUENCE.Functions.ActionProcedures
class SEQUENCE.Functions.ServiceProcedures
class SEQUENCE.Functions.TableBuilder

class SEQUENCE.LibraryDocumentation.ProcedureDependencies

class SEQUENCE.examples.ToBe
class SEQUENCE.examples.AsIs

class SEQUENCE.DemoSequence

@enduml