@startuml
skinparam linetype ortho
'left to right direction
package SEQUENCE {
    package Functions {
        abstract "SequenceLib_v3" as lib
        class "SequenceStyle" as style
        class "ParametresAndSwitchers" as params {
            id
            actionLength
            commentLength
            csvProcessDescription
            tableProcessDescription
            partiesMapper
            resultName
            requestHistory
            ainitiator
            aexecutor
            todoList
            todoId
        }
        class "AltProcedures" as alt
        class "ServiceProcedures" as serv {
            aliasToName
            textNewLineCutter
            todo
            }
        class "FunctionalProcedures" as function {
            parties - создание участников
            rq
            rs
            autors
            altrs
            proccessDescriptionBuilder
            todoNote
            NOTE
            partnote
            ----
            }
    }
}
class SEQUENCE.LibraryDocumentation.ProcedureDependencies
class SEQUENCE.LibraryDocumentation.examples.ToBe
class SEQUENCE.LibraryDocumentation.examples.AsIs
class SEQUENCE.DemoSequence

style *..|> lib
lib <|..* params
lib <|.* alt
lib <|.* serv
lib <|..* function

alt --> params
alt *-- function

function --> serv
function --> params

serv --> params

SEQUENCE.LibraryDocumentation -right- SEQUENCE.Functions

SEQUENCE.LibraryDocumentation.ProcedureDependencies -[hidden]- SEQUENCE.LibraryDocumentation.examples

SEQUENCE.DemoSequence --> SEQUENCE.Functions

@enduml0